# -*- coding: utf-8 -*-
"""Epsilon_optimizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14TyRYy3aFGN6eA8JJlVuvt9CpqqK_vPN
"""

import torch
from torch.optim.optimizer import Optimizer


class Epsilon(Optimizer):
    """
    Epsilon: adaptive optimiser based on the directional similarity of consecutive gradients.

    For each parameter tensor and step t:
        sim_t   = <g_t, g_{t-1}> / max(||g_t|| * ||g_{t-1}||, eps)       (Eq. 1)
        b_raw   = beta_max * sigmoid(alpha * sim_t)                      (Eq. 2)
        b_t     = clip(b_raw, beta_min, beta_max)                         (Eq. 3)
        m_t     = b_t * m_{t-1} + (1 - b_t) * g_t                        (Eq. 4)
        s_t     = ||g_t|| / (gamma + (1 - gamma) * ||m_t|| + eps)        (Eq. 5)
        theta_t = theta_{t-1} - lr * s_t * sign(m_t)                     (Eq. 6)

    Args:
        params: iterable of parameters to optimise.
        lr (float): learning rate (default: 1e-4).
        beta_max (float): upper bound of the momentum retention factor (default: 0.9).
        alpha (float): sensitivity of the sigmoid (default: 0.85).
        epsilon (float): numerical stability constant (default: 1e-8).
        beta_min (float): lower bound of the momentum retention factor (default: 0.5).
        gamma (float): balance between the constant and ||m_t|| in the step normalisation (default: 0.5).
    """

    def __init__(self, params, lr=1e-4, beta_max=0.9, alpha=0.85, epsilon=1e-8, beta_min=0.5, gamma=0.5):
        defaults = dict(lr=lr, beta_max=beta_max, alpha=alpha, epsilon=epsilon, beta_min=beta_min, gamma=gamma)
        super(Epsilon, self).__init__(params, defaults)

    @torch.no_grad()
    def step(self, closure=None):
        loss = None
        if closure is not None:
            with torch.enable_grad():
                loss = closure()

        for group in self.param_groups:
            lr = group['lr']
            beta_max = group['beta_max']
            alpha = group['alpha']
            eps = group['epsilon']
            beta_min = group['beta_min']
            gamma = group['gamma']

            for p in group['params']:
                if p.grad is None:
                    continue
                grad = p.grad
                state = self.state[p]

                if len(state) == 0:
                    state['momentum'] = torch.zeros_like(p)
                    state['prev_grad'] = torch.zeros_like(p)

                m = state['momentum']
                prev_g = state['prev_grad']

                # Eq. 1: directional similarity (computed per tensor)
                grad_norm = grad.norm()
                denom = (grad_norm * prev_g.norm()).clamp_min(eps)
                sim_dir = (grad * prev_g).sum() / denom

                # Eq. 2-3: adaptive momentum retention factor
                beta_t_raw = beta_max * (1 / (1 + torch.exp(-alpha * sim_dir)))
                beta_t = torch.clamp(beta_t_raw, min=beta_min, max=beta_max)

                # Eq. 4: adaptive first moment
                m.mul_(beta_t).add_(grad, alpha=1 - beta_t)

                # Eq. 5: scaled step magnitude
                s_t = grad_norm / (gamma + (1 - gamma) * m.norm() + eps)

                # Eq. 6: update along the sign of the momentum
                p.addcmul_(m.sign(), s_t * (-lr))

                state['prev_grad'] = grad.clone()

        return loss